---
title: "Untitled Draft"
author: "Report Author"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: docx
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = FALSE)
## target knits qmds in their own session, so load libraries here.
source(here::here("packages.R"))
## if you want access to the functions you've written
## lapply(list.files(here::here("./R"), full.names = TRUE), source)
```

```{r}
#| label: load-targets
#| include: false
# tar_load(c(target_1, target_2, target_3))

# # If your chunk output is shown in-line, then you'll need to wrap tar_load()
# # like so:
# 
# withr::with_dir(here::here(), {
#   tar_load(c(target_1, target_2, target_3))
# })
# 
# # This is not needed when using tar_make() to render the document.
```

```{r}
#| label: create_table
# Take the `islands` dataset and use some
# dplyr functionality to obtain the ten
# biggest islands in the world
islands_tbl <- 
  tibble(
    name = names(islands),
    size = islands
  ) %>%
  arrange(desc(size)) %>%
  slice(1:10)

# Display the table
islands_tbl
```

```{r}
#| label: gt_it
# Create a display table showing ten of
# the largest islands in the world
gt_tbl <- gt(islands_tbl)

# Show the gt Table
gt_tbl
```
